# Generated by Django 2.1.3 on 2019-08-17 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '出席'), (2, '欠席')], default=1, verbose_name='どちらかを選択ください'),
        ),
    ]
