# Generated by Django 2.1.3 on 2019-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190817_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.CharField(max_length=200, verbose_name='ご住所'),
        ),
        migrations.AlterField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ご芳名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, 'ご出席'), (2, 'ご欠席')], default=1, verbose_name='どちらかをお選びください'),
        ),
    ]
