# Generated by Django 2.1.3 on 2019-08-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190818_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tel',
            field=models.CharField(max_length=200, null=True, verbose_name='お電話'),
        ),
    ]
