# Generated by Django 2.1.3 on 2019-08-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='yubin',
            field=models.CharField(max_length=200, null=True, verbose_name='ご住所'),
        ),
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
