# Generated by Django 2.1.3 on 2019-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190819_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
    ]
